### ISSUE TITLE
bug: tags are not clickable

### ISSUE THREAD

**Issue by akshara-sun** [amilajack/tide#201]
## Expected

Tags provide a descriptive and easy way for users to find the sounds they are looking for without having to click through a track list and reading a description. **That being said, tags should be clickable.**

## How To Reproduce Bug

1. Click on any track on the Home Page.
2. Click on the tags displayed below the Sound Title (nothing happens when you do)

## To-Do

- [x] Make tags clickable.

**Comment by hamirmahal** [comment]
I believe #280 fixed this.
