### ISSUE TITLE
bug: tags don't change styles on hover

### ISSUE THREAD

**Issue by akshara-sun** [amilajack/tide#203]
## Expected 
When the mouse hovers over the tags, the tags should look clickable.

## How to Reproduce

1. Navigate to a sound by clicking on any track on the sound page
2. Hover mouse over tags (nothing happens)

## To-Do:

- [x] Tag styles should change on hover (preferred)
OR 

- [ ] Cursor can become a pointer 

_Linked with issue #201_

**Comment by hamirmahal** [comment]
> * [ ]  Tag styles should change on hover (preferred)

If we take this approach, I think we should have a design for what tag styles look like on hover on both day and night themes.

**Comment by hamirmahal** [comment]
I believe #280 fixed this.

**Comment by hamirmahal** [comment]
I think this issue is a duplicate of #201.
