### ISSUE TITLE
bug: play/pause shortcut key scrolls down page on Chrome after selecting sound from Pack or Similar lists

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/tide#211]
## Steps to reproduce bug

1. On Chrome or Chromium-based Edge, select a Pack or Similar sound from a sound's page, e.g., https://freesound-player.vercel.app/sound/120715.

2. Once the selected track's page loads, try to play or pause the selected track, using the `Space` key shortcut.

### Expected behavior
Pressing the `Space` key should play or pause the track appropriately.

### Actual behavior
Hitting `Space` scrolls down the page on Chrome or Chromium-based Edge.

Since [the `Space` key shortcut should only work `if (document.activeElement === document.body)`](https://github.com/amilajack/freesound-player/blob/0671c9c46cb73df96e289b79d5b8a23008cdd59c/src/Sound.js#L100), it appears the shortcut doesn't work because Chrome and Chromium-based Edge appear to give focus to selected sounds instead of to the document.

![Screen Shot 2020-11-19 at 11 44 22 AM](https://user-images.githubusercontent.com/43425812/99716121-93cd5f80-2a5c-11eb-9bdd-25f582527f86.png)

I've played around with a couple of different approaches.

While we could try to make the rule less restrictive as we discussed in our meeting, using something like

```
        if (
          document.activeElement !== document.getElementById("searchBar") &&
          document.activeElement !==
            document.getElementById("LoginConfirmationModal")
        ) {
```

instead of `if (document.activeElement === document.body)`, I think this becomes a bit too unwieldy and perhaps clutters `Sound.js` too much, especially if we add more focusable elements later. @amilajack and @akshara-sun, what do you think?

Instead, we could just make `document.activeElement === document.body` by doing the following after selecting a sound from the Pack or Similar lists on a sound's page: `document.activeElement.blur();`.

In effect, this means changing [`onSoundClick={() => window.scrollTo(0, 0)}` on line 188 of `Sound.js`](https://github.com/amilajack/freesound-player/blob/0671c9c46cb73df96e289b79d5b8a23008cdd59c/src/Sound.js#L188) to

```
        onSoundClick={() => {
          window.scrollTo(0, 0);
          document.activeElement.blur(); // Works; re-enables play/pause shortcut
        }}
```

For whatever reason, doing

```
        onSoundClick={() => {
          window.scrollTo(0, 0);
          document.body.focus(); // Does NOT work: `<a href="/sound/469002">…</a>` still has focus
        }}
```

doesn't work. `document.activeElement.blur();` enables the shortcut after selecting a sound from the Pack or Similar lists: `document.body.focus();` does not.

**Comment by amilajack** [comment]
@hamirmahal I dont think this is a bug anymore. closing but reopen if you think its still an issue
