### ISSUE TITLE
ui: current sound being viewed should be highlighted in packs SoundList

### ISSUE THREAD

**Issue by amilajack** [amilajack/tide#213]
## Expectation

If sound `x` is the current sound and sound `x` is in the pack SoundList, it should be accented

## Example

<img width="1604" alt="Screen Shot 2020-11-19 at 9 10 38 PM" src="https://user-images.githubusercontent.com/6374832/99761737-b20e7c00-2aab-11eb-9d0d-00df2b2d2300.png">

**Comment by hamirmahal** [comment]
We can also have it so that if the current sound is in the similar `<SoundList />` component, we can highlight it there, as well.
