### ISSUE TITLE
bug: sound list icons are broken on smaller viewports

### ISSUE THREAD

**Issue by akshara-sun** [amilajack/tide#214]
## How to Reproduce
1. Open DevTool.
2. Switch to smaller viewport. 
3. Icons will look wonky.

## Expected
Icons remain same size regardless of viewport.

**Comment by amilajack** [comment]
Please add screenshot

**Comment by akshara-sun** [comment]
### Standard Viewport
<img width="1333" alt="Screen Shot 2020-11-21 at 2 22 41 PM" src="https://user-images.githubusercontent.com/49100882/99888890-05e0a880-2c05-11eb-8bbe-977a9735b6b6.png">

### Smaller Viewport 
<img width="1085" alt="Screen Shot 2020-11-21 at 2 23 25 PM" src="https://user-images.githubusercontent.com/49100882/99888898-20b31d00-2c05-11eb-8ec3-9e63dcdb4e10.png">

**When you resize your window, the time icon shrink and eventually disappear.**
