### ISSUE TITLE
feat: login button dropdown

### ISSUE THREAD

**Issue by akshara-sun** [amilajack/tide#234]
### Idea
Once the user log's in, the Login button can change to showing "Hi _____", where the blank would be the user's name. This button will be a drop down menu that looks kind of like [this](https://codesandbox.io/s/headlessuireact-menu-example-b6xje?file=/src/App.js), where the options on the dropdown menu would be:

- My Profile (has the user's sounds, favorites, and info like email etc.)
- Account Settings (account security, deactivation etc.)
- Sign Out

**Comment by akshara-sun** [comment]
### Add profile picture instead of a greeting. 

#### Example:
<img width="262" alt="Screen Shot 2020-12-14 at 6 42 28 PM" src="https://user-images.githubusercontent.com/49100882/102161408-21258900-3e3c-11eb-917f-087f3e2f42c4.png">

Download Menu Options:
- Signed in as _______
- My Profile
- Account Settings
- Log Out

**Comment by amilajack** [comment]
@akshara-sun can you please simplify the title of the PR
