### ISSUE TITLE
bug: tab titles do not update when leaving sound pages

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/tide#269]
Tab titles do not change when searching, or visiting the homepage through this application's logo, after leaving a sound's page.

To see this in action, visit a sound page, e.g., [Music Note 5's sound page](https://tide-app.vercel.app/sound/462807), or, [Shepard Note A's sound page](https://tide-app.vercel.app/sound/376626), and either search something, or visit the homepage by clicking on this application's logo. In both cases, the tab's title retains the title it had on the sound's page.

Instead, the tab title should say we are on a search results page, or on the home page of the application, respectively.

The fix should be straightforward. We can `import { Helmet } from "react-helmet";` to `App.js`, and add
```
                <Helmet>
                  <title>Tide - Explore a world of sounds</title>
                  <meta name="description" content="Homepage of Tide" />
                </Helmet>
```
to the `render` of the `<Route>` with `path={"/"}`, similar to what we've already done in `Sound.js`.

Similarly, we can `import { Helmet } from "react-helmet";` to `SearchResults.js`, and add
```
      {showHeader && (
        <Helmet>
          <title>{`Search results for "${searchQuery || searchValue}"`}</title>
          <meta name="description" content="A sound from Tide" />
        </Helmet>
      )}
```
to it; we only update the tab title if we are showing search results while not on the homepage, which happens when `showHeader` is truthy.

We can probably remove `<title>Tide - Explore a world of sounds</title>` from line 180 of `index.html` since `react-helmet` should cover all of our tab's titles after making the changes just mentioned.

To make an implicit change explicit, if we do implement the above changes, `SearchResults.js` would need to return a React Fragment since we would be returning more than one element.

![image](https://user-images.githubusercontent.com/43425812/101686531-0909d000-3a1e-11eb-9bd0-7c13d0f0cea4.png)

![image](https://user-images.githubusercontent.com/43425812/101686365-cd6f0600-3a1d-11eb-9447-012586f2744e.png)

**Comment by akshara-sun** [comment]
@hamirmahal I really appreciate that you wrote this all out step-by-step for me, thank you so much! I am working on this right now and will hit you up with questions when they arise -- thanks again! #hamirIsAwesome 😉

**Comment by hamirmahal** [comment]
You're welcome! I added a couple of clarifying comments to the pull request we have open for this issue, #270.
