### ISSUE TITLE
investigate alternative data used for third sound-data icon, or use alternative icon altogether

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/tide#275]
We should use different sound data for the third sound icon in the `<SoundList />` component, or use a different `<Ionicon />` altogether.

![Screen Shot 2020-12-13 at 9 35 08 AM](https://user-images.githubusercontent.com/43425812/102019139-7f604800-3d26-11eb-9917-309bc104937a.png)

The third sound-data icon shows a play circle, which to me might imply the number of downloads, or the number of plays, but the actual data we show is the number of ratings, as we can tell from looking at [line 86 of `tide/src/SoundList.js`](https://github.com/amilajack/tide/blob/92fd65f65179db88c4ea6c9db9cfd6d624ea2b18/src/SoundList.js#L86), which says, `                  <span className="m-1">{track.num_ratings}</span>`.

The [Sound resources section of the Freesound API documentation](https://freesound.org/docs/api/resources_apiv2.html#sound-resources) says we can access the "Number of times the sound has been downloaded", which we already use, the "Number of times the sound has been rated", and the "Number of times the sound has been commented", among other things.

I haven't been able to find anything that says we can see the number of times a sound plays.

If we do want to use the "Number of times the sound has been rated", https://ionicons.com does have an `<ion-icon>` we can use.

![Screen Shot 2020-12-13 at 9 45 09 AM](https://user-images.githubusercontent.com/43425812/102019351-e5010400-3d27-11eb-8a9e-6ebba416755e.png)

**Comment by hamirmahal** [comment]
Which approach do we want to take?

**Comment by amilajack** [comment]
I think we should go with the star rating icon it is! What are your thoughts on that?

**Comment by hamirmahal** [comment]
Sounds good to me! Maybe @akshara-sun will want to take on the implementation?

**Comment by akshara-sun** [comment]
Star sounds like a great idea! Will get this issue in tonight!
