### ISSUE TITLE
sound header text is partially hidden

### ISSUE THREAD

**Issue by amilajack** [amilajack/tide#281]
![image](https://user-images.githubusercontent.com/6374832/102178690-b6377a80-3e5a-11eb-810a-eb26f5b56f69.png)

https://tide-app.vercel.app/sound/208519

**Comment by hamirmahal** [comment]
Nice catch! I didn't notice this before.

It seems to be really noticeable on tracks with g's and p's, like [arpeggio c a g _ in g major-01.wav](https://tide-app.vercel.app/sound/424190).

This is what the sound with id 424190 looks like at the time of this writing:

![Screen Shot of sound with id 424190 taken at 2020-12-15 at 9 11 38 AM](https://user-images.githubusercontent.com/43425812/102248012-8cf80800-3eb5-11eb-9a21-605b3ceeab32.png)

The header text doesn't appear hidden for [the same sound as above with the latest changes from #283](https://tide-git-header-styles-fixes.amilajack.vercel.app/sound/424190).

![Screen Shot of same sound as above with latest changes from #283 taken at 2020-12-15 at 9 13 35 AM](https://user-images.githubusercontent.com/43425812/102248243-d21c3a00-3eb5-11eb-808a-32457047759b.png)
